#!/usr/bin/python3

with open("/sys/class/backlight/intel_backlight/brightness","r") as brightness:
    value=brightness.read()
value = int(1.1*int(value))
if value < 10:
    value = 11
if value>9000:
    value=9000
with open("/sys/class/backlight/intel_backlight/brightness","w") as brightness:
    brightness.write(str(value))
