# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestGotocalendar():
  def setup_method(self, method):
    fireFoxOptions = webdriver.FirefoxOptions()
    fireFoxOptions.headless = True
    self.driver = webdriver.Firefox(options=fireFoxOptions)

    self.vars = {}
    self.driver.set_page_load_timeout(10)
    self.driver.implicitly_wait(10)
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_gotocalendar(self):
    try:
        self.driver.get("https://consulat.gouv.fr/consulat-general-de-france-a-amsterdam/rendez-vous")
#    self.driver.set_window_size(636, 1010)
        self.driver.find_element(By.XPATH, "//button[contains(.,\'Accéder aux services\')]").click()
        self.driver.find_element(By.XPATH, "//button[contains(.,\'Confirmer\')]").click()
        self.driver.find_element(By.CSS_SELECTOR, ".custom-control-label").click()
        self.driver.find_element(By.XPATH, "//button[contains(.,\'Prendre rendez-vous\')]").click()
    except NoSuchElementException:
        return
    self.driver.find_element(By.XPATH, "//p[contains(.,\'Tous les créneaux disponibles ont déjà été pris. Merci de réessayer ultérieurement.\')]").click()
  
