#!/usr/bin/python3

with open("/sys/class/backlight/intel_backlight/brightness","r") as brightness:
    value=brightness.read()
value = int(0.9*int(value))
if int(value) < 5:
    value=5

with open("/sys/class/backlight/intel_backlight/brightness","w") as brightness:
    brightness.write(str(value))
